baseURL = "http://example.org/"
languageCode = "en-us"
title = "Evangelia Verbi Athryridou"
theme = "massively"

[languages]
[languages.en]
  languageName = "English"
[languages.gr]
  languageName = "Ελληνικά"
  title = "Ευαγγελία Βέρπη Αθηρίδου"
