baseURL = "https://evangelia-verbi-athyridou.netlify.app/"
languageCode = "en-us"
title = "Evangelia Verbi Athryridou"
theme = "massively"

disableKinds = ['taxonomy', 'taxonomyTerm', 'section']

[languages]
[languages.en]
  languageName = "English"
[languages.gr]
  languageName = "Ελληνικά"
  title = "Ευαγγελία Βέρπη Αθηρίδου"
